name: Minify JavaScript

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Terser
        run: npm install terser -g

      - name: Minify JavaScript
        run: terser detectAutocomplete.js -o detectAutocomplete.min.js

      - name: Commit minified file
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add detectAutocomplete.min.js
          git commit -m "Minify JavaScript file" || echo "No changes to commit"
          git push